export const data = [
  {
    id: "1",
    title: "Hot",
    productname: "lip_liner",
    price: "230.99",
    product: "Women Lippie Pencil1",
    des: "Lippie Pencil A long-wearing high-intensity lip pencil glides on easily and prevents feathering.vsfsgg",
    img: "https://shorturl.at/vBLW4",
    product_type: "lip_liner",
  },
  {
    id: "2",
    brand: "colourpop",
    productname: "lipstick",
    price: "500.5",
    product: "Women Blotted Lip",
    des: "Blotted Lip Sheer matte lipstick that creates the perfect popsicle pout! Formula is lightweight",
    img: "https://shorturl.at/dyO18",
    product_type: "lipstick",
  },

  {
    id: "3",
    brand: "colourpop",
    productname: "Apple Watch",
    price: "500.5",
    product: "Women Blotted Lip1",
    des: "Blotted Lip Sheer matte lipstick that creates the perfect popsicle pout! Formula is lightweight",
    img: "https://rb.gy/o88bw6",
    product_type: "Apple Watch",
  },
  {
    id: "4",
    brand: "colourpop",
    productname: "Apple Watch i",
    price: "500.5",
    product: "Apple Watch",
    des: "boAt Wave Lite Smart Watch with 1.69 HD Display, Sleek Metal Body, HR & SpO2 Level Monitor, 140+ Watch Faces, Activity Tracker, Multiple Sports Modes, IP68 & 7 Days Battery Life",
    img: "http://rb.gy/x0i45y",
    product_type: "Apple Watch",
  },
  {
    id: "5",
    brand: "colourpop",
    productname: " Apple Watch Series 9",
    price: "500.5",
    product: " Apple Watch",
    des: "calories burnt & steps taken. Choose from multiple sports modes which include Walking, Running, Cycling, Climbing, Yoga, Basketball, Football & many more",
    img: "http://rb.gy/yi28mt",
    product_type: "Apple Watch",
  },
  {
    id: "6",
    brand: "colourpop",
    productname: "lipsticks",
    price: "500.5",
    product: "Women Lip",
    des: "Blotted Lip Sheer matte lipstick that creates the perfect popsicle pout! Formula is lightweight",
    img: "https://shorturl.at/dyO18",
    product_type: "lipstick",
  },
];
