// Manage action
export const GET_PRODUCT_PANDING = "GET_PRODUCT_PANDING"
export const GET_PRODUCT_FULLFILIED = "GET_PRODUCT_FULLFILIED"
export const GET_PRODUCT_REJECTED = "GET_PRODUCT_REJECTED"

//Manage action
export const POST_PRODUCT_PANDING = "POST_PRODUCT_PANDING"
export const POST_PRODUCT_FULLFILIED = "POST_PRODUCT_FULLFILIED"
export const POST_PRODUCT_REJECTED = "POST_PRODUCT_REJECTED"
